In [13]:
import h5py
import numpy as np
file = h5py.File('datasets/eccv16_dataset_tvsum_google_audio_pa_pool5 copy.h5', 'w')

with h5py.File('datasets/eccv16_dataset_tvsum_clip_audio_pa_pool5 copy.h5', 'r') as f:
    keys = list(f.keys())
    print(keys)
    for key in keys:
        g = file.create_group(key)
        print(list(f[key].keys()))
        columns = list(f[key].keys())
        for column in columns:
            print(f[key][column][()])
            if column != 'features':
                g.create_dataset(column, data=f[key][column][()])

with h5py.File('datasets/eccv16_dataset_summe_google_pool5.h5', 'r') as f:
    keys = list(f.keys())
    print(keys)
    for key in keys:
        print(list(f[key].keys()))
        columns = list(f[key].keys())
        for column in columns:
            print(f[key][column][()])
            if column == 'features':
                file[key].create_dataset(column, data=f[key][column][()])

['video_1', 'video_10', 'video_11', 'video_12', 'video_13', 'video_14', 'video_15', 'video_16', 'video_17', 'video_18', 'video_19', 'video_2', 'video_20', 'video_21', 'video_22', 'video_23', 'video_24', 'video_25', 'video_3', 'video_4', 'video_5', 'video_6', 'video_7', 'video_8', 'video_9']
['audio_features', 'change_points', 'features', 'gtscore', 'gtsummary', 'n_frame_per_seg', 'n_frames', 'n_steps', 'pascore', 'picks', 'user_summary', 'video_name']
[[0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 ...
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]]
[[   0  244]
 [ 245  473]
 [ 474  827]
 [ 828 1081]
 [1082 1233]
 [1234 1438]
 [1439 1530]
 [1531 16

In [18]:
with h5py.File('datasets/eccv16_dataset_summe_google_audio_pa_pool5 copy.h5', 'r') as f:
    keys = list(f.keys())
    print(keys)
    for key in keys:
        print(list(f[key].keys()))
        columns = list(f[key].keys())
        for column in columns:
            if column == 'features':
                print(f[key][column].shape)
            print(f[key][column][()])

['video_1', 'video_10', 'video_11', 'video_12', 'video_13', 'video_14', 'video_15', 'video_16', 'video_17', 'video_18', 'video_19', 'video_2', 'video_20', 'video_21', 'video_22', 'video_23', 'video_24', 'video_25', 'video_3', 'video_4', 'video_5', 'video_6', 'video_7', 'video_8', 'video_9']
['audio_features', 'change_points', 'features', 'gtscore', 'gtsummary', 'n_frame_per_seg', 'n_frames', 'n_steps', 'pascore', 'picks', 'user_summary', 'video_name']
[[0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 ...
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]]
[[   0  244]
 [ 245  473]
 [ 474  827]
 [ 828 1081]
 [1082 1233]
 [1234 1438]
 [1439 1530]
 [1531 16

In [17]:
with h5py.File('datasets/eccv16_dataset_summe_clip_audio_pa_pool5 copy.h5', 'r') as f:
    keys = list(f.keys())
    print(keys)
    for key in keys:
        print(list(f[key].keys()))
        columns = list(f[key].keys())
        for column in columns:
            if column == 'features':
                print(f[key][column].shape)
            print(f[key][column][()])

['video_1', 'video_10', 'video_11', 'video_12', 'video_13', 'video_14', 'video_15', 'video_16', 'video_17', 'video_18', 'video_19', 'video_2', 'video_20', 'video_21', 'video_22', 'video_23', 'video_24', 'video_25', 'video_3', 'video_4', 'video_5', 'video_6', 'video_7', 'video_8', 'video_9']
['audio_features', 'change_points', 'features', 'gtscore', 'gtsummary', 'n_frame_per_seg', 'n_frames', 'n_steps', 'pascore', 'picks', 'user_summary', 'video_name']
[[0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 ...
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]]
[[   0  244]
 [ 245  473]
 [ 474  827]
 [ 828 1081]
 [1082 1233]
 [1234 1438]
 [1439 1530]
 [1531 16

In [19]:
file.close()

In [4]:
import h5py
with h5py.File('datasets/eccv16_dataset_summe_clip_audio_pa_pool5 copy.h5', 'r') as f:
    keys = list(f.keys())
    print(keys)
    for key in keys:
        print(list(f[key].keys()))
        columns = list(f[key].keys())
        for column in columns:
            print(f[key][column][()])
            if column == 'audio_features':
                print(f[key][column][()].shape)
            if column == 'features':
                print(f[key][column][()].shape)

['video_1', 'video_10', 'video_11', 'video_12', 'video_13', 'video_14', 'video_15', 'video_16', 'video_17', 'video_18', 'video_19', 'video_2', 'video_20', 'video_21', 'video_22', 'video_23', 'video_24', 'video_25', 'video_3', 'video_4', 'video_5', 'video_6', 'video_7', 'video_8', 'video_9']
['audio_features', 'change_points', 'features', 'gtscore', 'gtsummary', 'n_frame_per_seg', 'n_frames', 'n_steps', 'pascore', 'picks', 'user_summary', 'video_name']
[[0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 [0.01897823 0.05166348 1.4561341  ... 1.3984165  0.21317327 1.6704671 ]
 ...
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]
 [0.00608499 0.08495386 1.7453953  ... 0.6690426  0.13594344 1.6877329 ]]
(300, 2048)
[[   0  244]
 [ 245  473]
 [ 474  827]
 [ 828 1081]
 [1082 1233]
 [1234 1438]
 [1439 153